<?php

namespace RealisationBundle\Repository;

/**
 * ImageRealisationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageRealisationRepository extends \Doctrine\ORM\EntityRepository
{
}
