imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@HomeBundle/Resources/config/services.yml" }
    - { resource: "@RealisationBundle/Resources/config/services.yml" }
    - { resource: "@ContactBundle/Resources/config/services.yml" }
    - { resource: "@SlideBundle/Resources/config/services.yml" }
    - { resource: "@ProductBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr
    image_realisations: '%kernel.project_dir%/web/uploads/realisations'
    image_sliders: '%kernel.project_dir%/web/uploads/sliders'
    image_products: '%kernel.project_dir%/web/uploads/products'


framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true
    templating:
        engines: ['twig']

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
        - 'bootstrap_4_layout.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    auth_mode: '%mailer_auth_mode%'
    host: '%mailer_host%'
    port: '%mailer_port%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    encryption: '%mailer_encryption%'
    spool: { type: memory }

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: HomeBundle\Entity\User
    from_email:
        address: "siracuse.harichandra@gmail.com"
        sender_name: "Apodec"
    service:
        mailer: fos_user.mailer.twig_swift
    profile:
        form:
            type: HomeBundle\Form\ProfileFormType
    resetting:
        email:
            template: email/password_resetting.email.twig
    registration:
        form:
            type: HomeBundle\Form\RegistrationFormType
        confirmation:
            enabled: true
            from_email:
                address: "%mailer_user%"
                sender_name: Administrateur
            template: email/registration.html.twig
    change_password:
        form:
            type: HomeBundle\Form\ChangePasswordFormType

fos_ck_editor:
    configs:
        my_config_1:
            toolbar: [
                        ['Bold', 'Italic', 'Underline'],
                        ['NumberedList','BulletedList','-','Outdent','Indent','-','-','JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock'],
                        ['Link']
                     ]
        my_config_2:
            toolbar: [
                    ['Source', 'NewPage', 'Preview'],
                    ['Undo', 'Redo'],
                    [ 'Button'],
                    ['TextColor', 'BGColor'],
                    ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-', 'BidiLtr', 'BidiRtl'],
                    ['Link' ],
                    ['Image', 'Table', 'SpecialChar' ],
                    ['Maximize', 'ShowBlocks']'/',
                    ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript'],
                    ['Styles', 'Format', 'Font', 'FontSize'],
                    ]

sensio_framework_extra:
   router:
        annotations: false
