<?php

namespace ProductBundle\Repository;

/**
 * ImageProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageProductRepository extends \Doctrine\ORM\EntityRepository
{
}
