<?php

namespace ProductBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function getActuAjax($data)
    {
        $qb = $this
            ->createQueryBuilder('a')
            ->where('a.name LIKE :data')
            ->setParameter('data', '%'.$data.'%')
        ;

        return $qb
            ->getQuery()
            ->getResult();
    }
}
